[package]
name = "client"
description = "Treeline player client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false
default-run = "client"

[features]
profiling = ["bevy/trace_tracy"]
webgpu = ["bevy/webgpu"]

[dependencies]
bevy = { workspace = true, features = ["bevy_dev_tools"] }
glam.workspace = true
libm.workspace = true
treeline-coordinates.workspace = true
treeline-ecology.workspace = true
treeline-climate.workspace = true
treeline-mesher.workspace = true
treeline-renderer.workspace = true
treeline-terrain.workspace = true
treeline-voxel.workspace = true
treeline-world.workspace = true
web-time.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Blob",
    "BlobPropertyBag",
    "console",
    "DedicatedWorkerGlobalScope",
    "HtmlElement",
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "Location",
    "MessageEvent",
    "Navigator",
    "Url",
    "Window",
    "Worker",
] }

[lints]
workspace = true
