[package]
name = "treeline-terrain"
description = "Functional signed-density and terrain material sampling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
treeline-coordinates.workspace = true

[lints]
workspace = true

