[package]
name = "treeline-protocol"
description = "Versioned multiplayer messages and replication contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
treeline-coordinates.workspace = true

[lints]
workspace = true

